# Generated by Django 4.2.2 on 2023-09-04 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('coin_amount', models.FloatField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'success'), (2, 'cancelled'), (3, 'failed')], default=0)),
                ('method', models.IntegerField(choices=[(0, 'deposit'), (1, 'withdraw')], default=0)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='base.currencysetting')),
            ],
            options={
                'db_table': 'transaction_log',
            },
        ),
    ]
