# Generated by Django 4.2.2 on 2023-09-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
