# Generated by Django 4.2.2 on 2023-10-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_transactionlog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
