# Generated by Django 4.2.2 on 2023-10-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_transactionlog_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlog',
            name='type',
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='type_id',
            field=models.IntegerField(default=0),
        ),
    ]
