# Generated by Django 4.2.2 on 2023-10-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_remove_transactionlog_type_transactionlog_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
