# Generated by Django 4.2.2 on 2023-10-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_transactionlog_tx_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='withdrawal_currency',
            field=models.IntegerField(choices=[(0, 'pga'), (1, 'usd')], default=0),
        ),
    ]
