# Generated by Django 4.2.2 on 2023-10-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_transactionlog_withdrawal_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='withdrawal_currency',
            field=models.IntegerField(choices=[(-1, 'none'), (0, 'pga'), (1, 'usd')], default=-1),
        ),
    ]
