# Generated by Django 4.2.2 on 2024-01-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('buy_price', models.FloatField(default=0)),
                ('size', models.CharField(max_length=128)),
                ('stock', models.FloatField(default=0)),
                ('cover_img', models.ImageField(upload_to='market/cover/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'market',
            },
        ),
    ]
