# Generated by Django 4.2.2 on 2023-09-04 11:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('buy_price', models.FloatField(default=0)),
                ('harvest_rate', models.FloatField(default=0)),
                ('stock', models.FloatField(default=0)),
                ('cover_img', models.ImageField(upload_to='seed/cover/')),
                ('vegetation_mass_period', models.IntegerField(default=0)),
                ('flowering_preharvest_period', models.IntegerField(default=0)),
                ('harvest_period', models.IntegerField(default=0)),
                ('drying_period', models.IntegerField(default=0)),
                ('curing_period', models.IntegerField(default=0)),
                ('packing_period', models.IntegerField(default=0)),
                ('purchased_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'seed',
            },
        ),
        migrations.CreateModel(
            name='SeedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_silica', models.SmallIntegerField(choices=[(0, 'not set'), (1, 'set')], default=0)),
                ('method_botanicare', models.SmallIntegerField(choices=[(0, 'not set'), (1, 'set')], default=0)),
                ('method_rhizo', models.SmallIntegerField(choices=[(0, 'not set'), (1, 'set')], default=0)),
                ('purchased_amount', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'seed_cart',
            },
        ),
        migrations.CreateModel(
            name='SeedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.IntegerField(default=0)),
                ('end_day', models.IntegerField(default=0)),
                ('growing_img', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'seed_media',
            },
        ),
        migrations.CreateModel(
            name='SeedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'completed'), (2, 'rejected')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'seed_sell_order',
            },
        ),
        migrations.CreateModel(
            name='SeedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_amount', models.FloatField(default=0)),
                ('profit', models.FloatField(default=0)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'purchased'), (1, 'ordered')], default=0)),
                ('method_silica', models.SmallIntegerField(choices=[(0, 'not set'), (1, 'set')], default=0)),
                ('method_botanicare', models.SmallIntegerField(choices=[(0, 'not set'), (1, 'set')], default=0)),
                ('method_rhizo', models.SmallIntegerField(choices=[(0, 'not set'), (1, 'set')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_user', to='shop.seed')),
            ],
            options={
                'db_table': 'seed_user',
            },
        ),
    ]
