# Generated by Django 4.2.2 on 2023-09-04 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seedorder',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_seed', to='shop.seeduser'),
        ),
        migrations.AddField(
            model_name='seedorder',
            name='seed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_order', to='shop.seed'),
        ),
        migrations.AddField(
            model_name='seedorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seedmedia',
            name='seed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_media', to='shop.seed'),
        ),
        migrations.AddField(
            model_name='seedcart',
            name='seed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_seed', to='shop.seed'),
        ),
        migrations.AddField(
            model_name='seedcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
