# Generated by Django 4.2.2 on 2023-09-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeduser',
            name='est_harvest_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
