# Generated by Django 4.2.2 on 2023-10-09 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_seedcart_payment_method_seedcart_pga_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seedcart',
            old_name='pga_price',
            new_name='price_sum',
        ),
        migrations.RemoveField(
            model_name='seedcart',
            name='usd_price',
        ),
    ]
