# Generated by Django 4.2.2 on 2023-10-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_pga_price_seedcart_price_sum_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seedcart',
            old_name='price_sum',
            new_name='price_pga',
        ),
        migrations.AddField(
            model_name='seedcart',
            name='price_usd',
            field=models.FloatField(default=0),
        ),
    ]
