# Generated by Django 4.2.2 on 2023-10-11 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_price_sum_seedcart_price_pga_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seedcart',
            old_name='price_pga',
            new_name='price_sum',
        ),
        migrations.RemoveField(
            model_name='seedcart',
            name='price_usd',
        ),
    ]
