# Generated by Django 4.2.2 on 2023-10-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_price_pga_seedcart_price_sum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedcart',
            name='method_botanicare',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seedcart',
            name='method_rhizo',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seedcart',
            name='method_silica',
            field=models.SmallIntegerField(default=0),
        ),
    ]
