# Generated by Django 4.2.2 on 2023-10-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_seedcart_method_botanicare_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedcart',
            name='method_botanicare',
            field=models.SmallIntegerField(choices=[(0, 'not set'), (1, 'set')], default=0),
        ),
        migrations.AlterField(
            model_name='seedcart',
            name='method_rhizo',
            field=models.SmallIntegerField(choices=[(0, 'not set'), (1, 'set')], default=0),
        ),
        migrations.AlterField(
            model_name='seedcart',
            name='method_silica',
            field=models.SmallIntegerField(choices=[(0, 'not set'), (1, 'set')], default=0),
        ),
    ]
