# Generated by Django 4.2.2 on 2023-10-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_seeduser_payment_method_seeduser_price_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeduser',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='seeduser',
            name='price_sum',
        ),
    ]
