# Generated by Django 4.2.2 on 2023-10-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_seeduser_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeduser',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(0, 'pga'), (1, 'usd')], default=0),
        ),
        migrations.AddField(
            model_name='seeduser',
            name='price_sum',
            field=models.FloatField(default=0),
        ),
    ]
