# Generated by Django 4.2.2 on 2023-10-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='type',
            field=models.IntegerField(choices=[(0, 'Purchase'), (1, 'Seed_Step'), (2, 'Sell_Harvest'), (3, 'Withdraw'), (4, 'Update_Profile'), (5, 'Ticket_Status'), (6, 'Deposit_Balance'), (7, 'Deposit_PGAToken')], default=0),
        ),
    ]
