# Generated by Django 4.2.2 on 2023-10-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_useragent_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_supportuser',
            field=models.BooleanField(default=False),
        ),
    ]
