# Generated by Django 4.2.2 on 2023-10-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_supportuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
